---
openapi: "3.0.1"
info:
  title: "STC Transaction Summary"
  description: "This API specification describes the data structures and operations\
    \ to interact with a taxpayer’s STC Transaction Summary.\n \nThere are at present\
    \ the following operations: \n\n1. Retrieve the taxpayer's STC Transaction Summary\
    \ details.\n\n**EPID references: ** \n\n- EPID1681- HIP OAS: STC Transaction Summary.\n\
    \n\n```\nChange Log\n```\n| Version | Date | Author | Description |\n|---|-----|------|-----|\n\
    |0.1.0 | 09-03-2026 |Kiran Reddy| Initial draft. |\n|0.2.0 | 17-03-2026 |Arati\
    \ Pradhan| Updated for internal review and large payload handling by splitting\
    \ request. |\n|0.3.0 | 18-03-2026 |Arati Pradhan| Updated for internal review\n|0.4.0 | 15-04-2026 |Arati Pradhan| Updated OAS change log dates\n"
  version: "0.4.0"
  termsOfService: "http://INSERT_LINK_TO_SLA_HERE"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0"
  x-integration-catalogue:
    api-type: "SIMPLE"
    backends:
    - "ETMP"
    domain: "2.0"
    platform: "HIP"
    publisher-reference: "EPID 1681 -STC Transaction Summary API"
    reviewed-date: "2026-03-18T18:28:00Z"
    short-description: "STC Transaction Summary API "
    status: "BETA"
    sub-domain: "2.26"
servers:
- url: "http://etmp-egress-gateway.egress.svc.cluster.local"
  description: "Egress Gateway to ETMP TEST"
tags:
- name: "STC Transaction Summary"
  description: "Securities Transfer Charge : Transaction Summary"
paths:
  /RESTAdapter/stc/transaction/summary/{stcId}:
    parameters:
    - name: "stcId"
      in: "path"
      description: "STC Reference ID"
      required: true
      deprecated: false
      allowEmptyValue: false
      style: "simple"
      schema:
        type: "string"
        minLength: 1
        maxLength: 15
      example: "XASTC0012345678"
    get:
      deprecated: false
      summary: "Consumer to ETMP STC Transaction Summary "
      description: "This operation allows taxpayer to STC Transaction Summary details\
        \ on ETMP-SAFE. \\\nThe call is synchronous.\nIf successful, the API will\
        \ return the processing date/time, STC transaction summary details.\nIf unsuccessful,\
        \ the API will return the processing date/time, error code and text.\n\n**EPID\
        \ reference: **\n- EPID1683 - STC Transaction Summary API\n"
      operationId: "STCTransactionSummary"
      tags:
      - "STC Transaction Summary"
      parameters:
      - name: "X-Originating-System"
        in: "header"
        description: "System that is the originator of the message. This should be\
          \ the consumer of the API Example \"STC\""
        required: true
        deprecated: false
        allowEmptyValue: false
        style: "simple"
        schema:
          minLength: 1
          maxLength: 30
          type: "string"
        example: "MDTP-STC"
      - name: "X-Transmitting-System"
        in: "header"
        description: "Intermediary system that performs the transmission of the message."
        required: true
        deprecated: false
        allowEmptyValue: false
        style: "simple"
        schema:
          enum:
          - "HIP"
          type: "string"
      - name: "X-Receipt-Date"
        in: "header"
        description: "The time the message was created by the system sending the message.\
          \ The value should follow this date-time pattern, and be represented in\
          \ the UTC time zone: yyyy-MM-ddTHH:mm:ssZ"
        required: true
        deprecated: false
        allowEmptyValue: false
        style: "simple"
        schema:
          format: "date-time"
          type: "string"
        example: "2025-01-30T23:59:59Z"
      - name: "correlationid"
        in: "header"
        description: "Unique alphanumeric ID for traceability and debugging.\nMust\
          \ be generated by the originating system.\nMust conform to 36-character\
          \ UUID format."
        required: true
        deprecated: false
        allowEmptyValue: false
        style: "simple"
        schema:
          pattern: "^[0-9a-fA-F]{8}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{12}$"
          type: "string"
        example: "f0bd1f32-de51-45cc-9b18-0520d6e3ab1a"
      - name: "p1"
        in: "query"
        description: "p1"
        required: true
        deprecated: false
        allowEmptyValue: false
        style: "form"
        schema:
          type: "string"
          description: "Param 1"
          minLength: 1
          maxLength: 20
          enum:
          - "submissionId"
          - "submissionDateRange"
          - "clientReference"
          - "utrn"
          - "buyerName"
          - "sellerName"
          - "companyName"
        example: "submissionId"
      - name: "v1"
        in: "query"
        description: "v1"
        required: true
        deprecated: false
        allowEmptyValue: false
        style: "form"
        schema:
          type: "string"
          description: "Value for Param 1"
          minLength: 1
          maxLength: 100
        example: "123456789012"
      - name: "p2"
        in: "query"
        description: "p2"
        required: false
        deprecated: false
        allowEmptyValue: false
        style: "form"
        schema:
          type: "string"
          description: "Param 2"
          minLength: 1
          maxLength: 20
          enum:
          - "buyerName"
          - "sellerName"
          - "companyName"
        example: "buyerName"

      - name: "v2"
        in: "query"
        description: "v2"
        required: false
        deprecated: false
        allowEmptyValue: false
        style: "form"
        schema:
          type: "string"
          description: "Value for Param 2"
          minLength: 1
          maxLength: 100
        example: "Peter Smith"

      - name: "batchCount"
        in: "query"
        description: "Batch Count"
        required: false
        deprecated: false
        allowEmptyValue: false
        style: "form"
        schema:
          description: "batch size"
          type: "number"
          minimum: 0
          maximum: 999
        example: 1
      - name: "batchSize"
        in: "query"
        description: "Batch Size"
        required: false
        deprecated: false
        allowEmptyValue: false
        style: "form"
        schema:
          description: "batch size"
          type: "number"
          minimum: 0
          maximum: 999
        example: 200

      responses:
        "200":
          description: "ETMP has successfully accepted the request to display the\
            \ STC transactional summary data and successfully process request further."
          headers:
            correlationid:
              $ref: "#/components/headers/correlationid-type"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/schema-stc-transaction-summary-response-success-200"
              examples:
                sample-stc-transaction-summary-response-success-200:
                  $ref: "#/components/examples/sample-stc-transaction-summary-response-success-200"
                Example2-Made-Up:
                  $ref: "#/components/examples/sample-stc-transaction-summary-response-success-toomany-utrn-200"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  error:
                    description: "SAP PI System Error Response"
                    type: "object"
                    properties:
                      code:
                        description: "If HTTP400, then code value will be 400."
                        type: "string"
                        enum:
                        - "400"
                      message:
                        type: "string"
                        minLength: 1
                        maxLength: 5000
                      logID:
                        type: "string"
                        minLength: 32
                        maxLength: 32
                        pattern: "^[A-F0-9]{32}$"
                    required:
                    - "code"
                    - "message"
                    - "logID"
                    additionalProperties: false
                required:
                - "error"
                additionalProperties: false
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
        "422":
          description: "ETMP validation errors. \nErrors of this kind indicate that\
            \ ETMP successfully received the data without any technical issues, however\
            \ it is unable to process the data further for the reason given by the\
            \ code and text.\n\n```\n[ code | text]\n001 | STC ID does not exist\n\
            002 | Submission Date Range incorrect\n002 | UTRN incorrect\n002 | Buyer\
            \ Name incorrect\n002 | Seller Name incorrect\n002 | Company Name incorrect\n\
            003 | Batch Count incorrect\n003 | Batch Size incorrect"
          headers:
            correlationid:
              $ref: "#/components/headers/correlationid-type"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/schema-stc-transaction-summary-response-error-422"
              examples:
                sample-stc-transaction-summary-response-error-422:
                  $ref: "#/components/examples/sample-stc-transaction-summary-response-error-422"
        "500":
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  error:
                    description: "SAP PI System Error Response"
                    type: "object"
                    properties:
                      code:
                        description: "If HTTP500, then code value will be 500."
                        type: "string"
                        enum:
                        - "500"
                      message:
                        type: "string"
                        minLength: 1
                        maxLength: 5000
                      logID:
                        type: "string"
                        minLength: 32
                        maxLength: 32
                        pattern: "^[A-F0-9]{32}$"
                    required:
                    - "code"
                    - "message"
                    - "logID"
                    additionalProperties: false
                required:
                - "error"
                additionalProperties: false
components:
  headers:
    correlationid-type:
      description: "Unique alphanumeric number used for correlation purposes, generated\
        \ by the originating system and conforming to 36-character UUID (formatted)."
      style: "simple"
      required: false
      deprecated: false
      schema:
        pattern: "^[0-9a-fA-F]{8}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{12}$"
        type: "string"
      example: "f0bd1f32-de51-45cc-9b18-0520d6e3ab1a"
  schemas:
    buyers-name-type:
      description: "If there are more than one buyer, all buyer name to be sent separted\
        \ by comma.Truncation may occur as max length is 255 char"
      type: "string"
      minLength: 1
      maxLength: 255
    charge-amount-type:
      description: "Amount(11 Digits before Decimal and 2 after decimal)"
      type: "number"
      minimum: 0.0
      maximum: 9.999999999999E10
      multipleOf: 0.01
    charge-details-summary-type:
      type: "object"
      properties:
        utrn:
          $ref: "#/components/schemas/utrn-type"
        chargeTypeDescription:
          description: "Charges Type Description"
          $ref: "#/components/schemas/charge-type-description"
        chargeReference:
          description: "Transaction reference"
          $ref: "#/components/schemas/charge-reference-type"
        chargeType:
          description: "Transaction Type "
          $ref: "#/components/schemas/charge-transaction-type"
        chargeAmountTotal:
          $ref: "#/components/schemas/charge-amount-type"
        chargeDueDate:
          $ref: "#/components/schemas/charge-due-date-type"
        chargeAmountPending:
          $ref: "#/components/schemas/charge-amount-type"
      required:
      - "utrn"
      - "chargeTypeDescription"
      - "chargeReference"
      - "chargeType"
      - "chargeAmountTotal"
      - "chargeDueDate"
      - "chargeAmountPending"
      additionalProperties: false
    charge-due-date-type:
      description: "Charge due date"
      type: "string"
      format: "date"
    charge-reference-type:
      description: "Charge reference"
      type: "string"
      minLength: 1
      maxLength: 16
    charge-transaction-type:
      description: "Charge transaction"
      type: "string"
      minLength: 1
      maxLength: 40
    charge-type-description:
      description: "Charge type description"
      type: "string"
      minLength: 1
      maxLength: 40
    client-reference-type:
      type: "string"
      minLength: 1
      maxLength: 255
    company-name-type:
      type: "string"
      minLength: 1
      maxLength: 105
    date-time-type:
      type: "string"
      pattern: "^[0-9]{4}-([0][1-9]|[1][0-2])-([0][1-9]|[1-2][0-9]|[3][0-1])T([0-1][0-9]|[2][0-3]):[0-5][0-9]:[0-5][0-9]Z$"
      format: "date-time"
    declaree-name-type:
      type: "string"
      minLength: 1
      maxLength: 255
    message-type:
      description: "message n"
      type: "string"
      minLength: 1
      maxLength: 100
    schema-stc-transaction-summary-response-error-422:
      description: "STC transaction summary business error HIPEPID1681,Internal EPID1683,\
        \ Fspec D2009, "
      type: "object"
      properties:
        errors:
          $ref: "#/components/schemas/stc-transaction-summary-business-error-types"
    schema-stc-transaction-summary-response-success-200:
      description: "STC Transaction Summary  Response HIP OAS EPID1681 ,Internal EPID1683\
        \ , FSD2009,  Response code 200"
      type: "object"
      properties:
        success:
          description: "Transaction request successfully processed in ETMP "
          type: "object"
          properties:
            processingDate:
              $ref: "#/components/schemas/date-time-type"
            transactionsCount:
              $ref: "#/components/schemas/transactions-count-type"
            message:
              $ref: "#/components/schemas/message-type"
            transactionDetails:
              type: "array"
              minItems: 0
              items:
                $ref: "#/components/schemas/transaction-details-summary-type"
            charges:
              description: "charges"
              type: "array"
              minItems: 0
              items:
                $ref: "#/components/schemas/charge-details-summary-type"
          required:
          - "processingDate"
          - "transactionsCount"
      additionalProperties: false
    sellers-name-type:
      type: "string"
      description: "If there are more than one seller, all seller name to be sent\
        \ separted by comma.Truncation may occur as max length is 255 char"
      minLength: 1
      maxLength: 255
    stc-transaction-summary-business-error-types:
      type: "object"
      properties:
        processingDate:
          description: "SAP PI and ETMP require date-time in a format with Z as the\
            \ suffix example 2020-12-30T12:34:56Z."
          type: "string"
          pattern: "^[0-9]{4}-([0][1-9]|[1][0-2])-([0][1-9]|[1-2][0-9]|[3][0-1])T([0-1][0-9]|[2][0-3]):[0-5][0-9]:[0-5][0-9]Z$"
          format: "date-time"
        code:
          description: "Business errors"
          type: "string"
          enum:
          - "001"
          - "002"
          - "003"
        text:
          type: "string"
          minLength: 1
          maxLength: 255
      required:
      - "processingDate"
      - "code"
      - "text"
      additionalProperties: false
    submission-date-type:
      type: "string"
      format: "date"
    submission-id-type:
      type: "string"
      minLength: 1
      maxLength: 12
    transaction-details-summary-type:
      type: "object"
      properties:
        submissionId:
          $ref: "#/components/schemas/submission-id-type"
        submissionDate:
          $ref: "#/components/schemas/submission-date-type"
        clientReference:
          $ref: "#/components/schemas/client-reference-type"
        declareeName:
          $ref: "#/components/schemas/declaree-name-type"
        utrn:
          $ref: "#/components/schemas/utrn-type"
        buyerNames:
          $ref: "#/components/schemas/buyers-name-type"
        sellerNames:
          $ref: "#/components/schemas/sellers-name-type"
        companyName:
          $ref: "#/components/schemas/company-name-type"
      required:
      - "submissionId"
      - "submissionDate"
      - "declareeName"
      - "utrn"
      - "buyerNames"
      - "companyName"
      additionalProperties: false
    transactions-count-type:
      description: "Number of transactions in the response (0 to 99999999) "
      type: "number"
      minimum: 0
      maximum: 99999999
      multipleOf: 0.01
    utrn-type:
      description: "utrn"
      type: "string"
      minLength: 1
      maxLength: 12
  examples:
    sample-stc-transaction-summary-response-error-422:
      summary: "sample-stc-transaction-summary-response-error-422"
      description: "ETMP Bussiness Error"
      value:
        errors:
          processingDate: "2025-10-31T09:30:47Z"
          code: "001"
          text: "STC ID does not exist"
    sample-stc-transaction-summary-response-success-200:
      summary: "sample-stc-transaction-summary-response-success-200"
      value:
        success:
          processingDate: "2001-12-17T09:30:47Z"
          transactionsCount: 2
          transactionDetails:
          - submissionId: "123456789012"
            submissionDate: "2026-02-28"
            clientReference: "AGRN1212091"
            declareeName: "James White"
            utrn: "900459020010"
            buyerNames: "John White"
            sellerNames: "Mary Philips"
            companyName: "Apple Ltd"
          - submissionId: "123456789013"
            submissionDate: "2026-02-28"
            clientReference: "AGRN1212092"
            declareeName: "James White"
            utrn: "900459020011"
            buyerNames: "John White,Dan J Philips"
            sellerNames: "Peter White,Mary Philips"
            companyName: "Apple Ltd"
          charges:
          - utrn: "900459020010"
            chargeTypeDescription: "STC Non-contingent charges"
            chargeReference: "XY007000075424"
            chargeType: "LFP"
            chargeAmountTotal: 350.78
            chargeDueDate: "2026-02-28"
            chargeAmountPending: 125.96
          - utrn: "900459020011"
            chargeTypeDescription: "STC Non-contingent charges"
            chargeReference: "XY007000075425"
            chargeType: "LFP"
            chargeAmountTotal: 450.78
            chargeDueDate: "2026-02-28"
            chargeAmountPending: 225.96
    sample-stc-transaction-summary-response-success-toomany-utrn-200:
      summary: "sample-stc-transaction-summary-response-success-toomany-utrn-200"
      value:
        success:
          processingDate: "2001-12-17T09:30:47Z"
          transactionsCount: 99999999
          message: "Too many Formbundles to display"
